apiVersion: apps/v1
kind: Deployment
metadata:
  name: container-1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: container-1
  template:
    metadata:
      labels:
        app: container-1
    spec:
      containers:
        - name: container-1
          image: us-central1-docker.pkg.dev/my-gke-project-454300/microservices-repo/container1:latest
          ports:
            - containerPort: 6000
          volumeMounts:
            - mountPath: "/anupam_PV_dir"
              name: standard-volume
      volumes:
        - name: standard-volume
          persistentVolumeClaim:
            claimName: anupam-pvc
      nodeSelector:
        cloud.google.com/gke-nodepool: "primary-node-pool" # Ensure pods run on the correct node pool
